BEGIN TRANSACTION;
CREATE SCHEMA SCHEMACHANGE.TEST_SCHEMA;
CREATE TABLE SCHEMACHANGE.TEST_SCHEMA.TEST_TABLE(key text, val text);
INSERT INTO SCHEMACHANGE.TEST_SCHEMA.TEST_TABLE VALUES ('1','a');
CREATE SCHEMA SCHEMACHANGE.TEST_SCHEMA2;
CREATE DATABASE SC_DEMO;
COMMIT;
